image: node:12-stretch

pages:
  tags:
    - docker
  stage: deploy
  script:
    - npm ci
    - npm run build:docs
    - npm run build:storybook
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - develop
